#!/bin/bash
# build kernel for all devices

. setenv

DEVICES="xpress loox_plus next loox"
MAKE_OPTIONS="-j2"
KERNEL_PATH="../kernels"
if [ "" == "$1" ]; then
  rev=TEST
else
  rev="$1"
fi

make distclean
# loop through each device
for device in ${DEVICES} ; do
  echo "*** Building kernel for device: ${device} ***"
  # make mrproper
  rm kernel.img
  make odys_${device}_defconfig
  make ${MAKE_OPTIONS} kernel.img modules 2>&1 | tee build.log
  
  # abort on missing make result
  if [ ! -f kernel.img ]; then echo "ABORTED WITH ERROR"; exit; fi
  
  # archive kernel.img
  mkdir -p ${KERNEL_PATH}/${device}
  cp kernel.img ${KERNEL_PATH}/${device}/
  7z a ${KERNEL_PATH}/kernel_308_${device}_${rev}.7z kernel.img

  # tag current git state with delivery tag
  git tag ${device}_${rev}
done
# create package of all available modules
MODULES=`find . -name '*.ko'`
7z a ${KERNEL_PATH}/modules_308_${rev}.7z ${MODULES}


